"""create expenses

Revision ID: d5502863913f
Revises: 
Create Date: 2025-11-02 11:15:50.558957

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd5502863913f'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('expenses',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('spent_on', sa.Date(), nullable=False),
        sa.Column('vendor', sa.String(length=120), nullable=False),
        sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column('currency', sa.String(length=8), nullable=False),
        sa.Column('memo', sa.String(length=255), nullable=True),
        sa.PrimaryKeyConstraint('id')
    )
        # op.drop_table('playing_with_neon') # 存在しないテーブルの削除をスキップ
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('playing_with_neon',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('value', sa.REAL(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('playing_with_neon_pkey'))
    )
    op.drop_table('expenses')
    # ### end Alembic commands ###
